In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
data = pd.read_csv('train.csv',usecols=["X1","X2","X3","X4","X5","X6"])
data.head()

  X1  X2 X3 X4 X5 X6
0  v  at  a  d  u  j
1  t  av  e  d  y  l
2  w   n  c  d  x  j
3  t   n  f  d  x  l
4  v   n  f  d  h  d

In [4]:
#lets understand that at how many labels each variables have
for col in data.columns:
    print(col,':',len(data[col].unique()),'labels')

X1 : 27 labels
X2 : 44 labels
X3 : 7 labels
X4 : 4 labels
X5 : 29 labels
X6 : 12 labels

In [5]:
#Lets examine how many columns we will obtain one hot encoding these variables
pd.get_dummies(data,drop_first=True).shape

(4209, 117)

In [6]:
#Lets find top 10 most frequest categories for the variable
data.X2.value_counts().sort_values(ascending=False).head(20)

X2
as    1659
ae     496
ai     415
m      367
ak     265
r      153
n      137
s       94
f       87
e       81
aq      63
ay      54
a       47
t       29
k       25
i       25
b       21
ao      20
z       19
ag      19
Name: count, dtype: int64

In [7]:
#lets make a list with the most frequents categories of the variable
top_10 = [x for x in data.X2.value_counts().sort_values(ascending = False).head(10).index]
top_10

['as', 'ae', 'ai', 'm', 'ak', 'r', 'n', 's', 'f', 'e']

In [8]:
#and now we make 10 binary variable
for label in top_10:
    data[label] = np.where(data['X2'] == label,1,0)
data[['X2']+top_10].head(40)

    X2  as  ae  ai  m  ak  r  n  s  f  e
0   at   0   0   0  0   0  0  0  0  0  0
1   av   0   0   0  0   0  0  0  0  0  0
2    n   0   0   0  0   0  0  1  0  0  0
3    n   0   0   0  0   0  0  1  0  0  0
4    n   0   0   0  0   0  0  1  0  0  0
5    e   0   0   0  0   0  0  0  0  0  1
6    e   0   0   0  0   0  0  0  0  0  1
7   as   1   0   0  0   0  0  0  0  0  0
8   as   1   0   0  0   0  0  0  0  0  0
9   aq   0   0   0  0   0  0  0  0  0  0
10   r   0   0   0  0   0  1  0  0  0  0
11   e   0   0   0  0   0  0  0  0  0  1
12  ai   0   0   1  0   0  0  0  0  0  0
13   e   0   0   0  0   0  0  0  0  0  1
14  as   1   0   0  0   0  0  0  0  0  0
15  ak   0   0   0  0   1  0  0  0  0  0
16   e   0   0   0  0   0  0  0  0  0  1
17  as   1   0   0  0   0  0  0  0  0  0
18   m   0   0   0  1   0  0  0  0  0  0
19  ak   0   0   0  0   1  0  0  0  0  0
20   m   0   0   0  1   0  0  0  0  0  0
21  as   1   0   0  0   0  0  0  0  0  0
22   a   0   0   0  0   0  0  0  0  0  0
23   m   0   0   0  1   0  0  0  0  0  0
24  ak   0   0   0  0   1  0  0  0  0  0
25   m   0   0   0  1   0  0  0  0  0  0
26  as   1   0   0  0   0  0  0  0  0  0
27  as   1   0   0  0   0  0  0  0  0  0
28  as   1   0   0  0   0  0  0  0  0  0
29   m   0   0   0  1   0  0  0  0  0  0
30  as   1   0   0  0   0  0  0  0  0  0
31  as   1   0   0  0   0  0  0  0  0  0
32   m   0   0   0  1   0  0  0  0  0  0
33  as   1   0   0  0   0  0  0  0  0  0
34  as   1   0   0  0   0  0  0  0  0  0
35  ai   0   0   1  0   0  0  0  0  0  0
36  as   1   0   0  0   0  0  0  0  0  0
37   k   0   0   0  0   0  0  0  0  0  0
38  as   1   0   0  0   0  0  0  0  0  0
39  as   1   0   0  0   0  0  0  0  0  0

In [9]:
#get whole set of dummy variable ,for all the categorical variable
def one_hot_top_x(df,variable,top_10):

 #function to create the dummy variable for the most frequent labels
 # we can vary the number of most frequent labels that we encode
   for label in top_10:
      df[variable+'_'+label] = np.where(data[variable] == label,1,0)

#read the data again
data = pd.read_csv('train.csv',usecols=["X1","X2","X3","X4","X5","X6"])

#encode X2 into the 10 most frequent categories
one_hot_top_x(data,'X2','top_10')
data.head()

  X1  X2 X3 X4 X5 X6  X2_t  X2_o  X2_p  X2__  X2_1  X2_0
0  v  at  a  d  u  j     0     0     0     0     0     0
1  t  av  e  d  y  l     0     0     0     0     0     0
2  w   n  c  d  x  j     0     0     0     0     0     0
3  t   n  f  d  x  l     0     0     0     0     0     0
4  v   n  f  d  h  d     0     0     0     0     0     0

In [10]:
#find the 10 most frequent categories for x1
top_10 = [x for x in data.X1.value_counts().sort_values(ascending=False).head(10).index]

one_hot_top_x(data,'X1',top_10)
data.head()

,X1,X2,X3,X4,X5,X6,X2_t,X2_o,X2_p,X2__,...,X1_aa,X1_s,X1_b,X1_l,X1_v,X1_r,X1_i,X1_a,X1_c,X1_o
0,v,at,a,d,u,j,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1,t,av,e,d,y,l,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,w,n,c,d,x,j,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,t,n,f,d,x,l,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,v,n,f,d,h,d,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [11]:
df = pd.read_csv('train.csv',usecols=['X1','X2'])
df.head()

  X1  X2
0  v  at
1  t  av
2  w   n
3  t   n
4  v   n

In [12]:
df.shape

(4209, 2)

One Hot Encoding

In [13]:
pd.get_dummies(df).shape

(4209, 71)

In [14]:
len(df['X1'].unique())

27

In [15]:
len(df['X2'].unique())

44

In [16]:
#lets have a look on how many labels
for col in df.columns:
    print(col,':',len(df[col].unique()),'labels')

X1 : 27 labels
X2 : 44 labels

In [17]:
#lets obtain the counts for each one of the labels in variable X2
#lets capture this in a dictionary that we can use to remap the labels
df.X2.value_counts().to_dict()

{'as': 1659,
 'ae': 496,
 'ai': 415,
 'm': 367,
 'ak': 265,
 'r': 153,
 'n': 137,
 's': 94,
 'f': 87,
 'e': 81,
 'aq': 63,
 'ay': 54,
 'a': 47,
 't': 29,
 'k': 25,
 'i': 25,
 'b': 21,
 'ao': 20,
 'z': 19,
 'ag': 19,
 'd': 18,
 'ac': 13,
 'g': 12,
 'ap': 11,
 'y': 11,
 'x': 10,
 'aw': 8,
 'at': 6,
 'h': 6,
 'q': 5,
 'al': 5,
 'an': 5,
 'av': 4,
 'p': 4,
 'ah': 4,
 'au': 3,
 'am': 1,
 'j': 1,
 'af': 1,
 'l': 1,
 'aa': 1,
 'c': 1,
 'o': 1,
 'ar': 1}

In [18]:
#and Now replace each label  in x2 by its count 
df_frequency_map = df.X2.value_counts().to_dict()

In [19]:
#and now we replace X2 labels in the dataset df
df.X2 = df.X2.map(df_frequency_map)
df.head(100)

    X1    X2
0    v     6
1    t     4
2    w   137
3    t   137
4    v   137
..  ..   ...
95   b   367
96   l  1659
97  aa  1659
98   b   367
99   s   367

[100 rows x 2 columns]

Handling missing values --- features engineering

What are different types of Missing Data?

Missing Completly at random

In [20]:
# Missing Completly at Random, MCAR:
df = pd.read_csv('Titanic-Dataset.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [21]:
#for finding missing number
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [22]:
df[df['Embarked'].isnull()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
61,62,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0,B28,NaN
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0,B28,NaN

2.Missing Data not at Rndom(MNAR):Systematic missing values

In [23]:
df['Cabin']

0       NaN
1       C85
2       NaN
3      C123
4       NaN
       ...
886     NaN
887     B42
888     NaN
889    C148
890     NaN
Name: Cabin, Length: 891, dtype: object

In [24]:
df['Cabin_null'] = np.where(df['Cabin'].isnull(),1,0)

##find the percentage of null values
df['Cabin_null'].mean()

np.float64(0.7710437710437711)

In [25]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'Cabin_null'],
      dtype='object')

In [26]:
df.groupby(['Survived'])['Cabin_null'].mean()

Survived
0    0.876138
1    0.602339
Name: Cabin_null, dtype: float64

Missing at Random

All techniques of handling missing values

In [27]:
df = pd.read_csv('Titanic-Dataset.csv',usecols=['Age','Fare','Survived'])
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [28]:
## lets go and see percentage of missing number
df.isnull().mean()

Survived    0.000000
Age         0.198653
Fare        0.000000
dtype: float64

In [29]:
def impute_nan(df,variable,median):
    df[variable+'_median'] = df[variable].fillna(median)

In [30]:
median = df.Age.median()
median

28.0

In [31]:
impute_nan(df,'Age',median)
df.head()

   Survived   Age     Fare  Age_median
0         0  22.0   7.2500        22.0
1         1  38.0  71.2833        38.0
2         1  26.0   7.9250        26.0
3         1  35.0  53.1000        35.0
4         0  35.0   8.0500        35.0

In [32]:
print(df['Age'].std())
print(df['Age_median'].std())

14.526497332334044
13.019696550973194

In [33]:
fig = plt.figure()
ax = fig.add_subplot(111)
df['Age'].plot(kind = 'kde',ax = ax)
df.Age_median.plot(kind = 'kde',ax = ax,color = 'red')
lines,labels = ax.get_legend_handles_labels()
ax.legend(lines,labels,loc = 'best')

In [37]:
bigmart = pd.read_csv('Train_bm_bigmart')

FileNotFoundError: [Errno 2] No such file or directory: 'Train_bm_bigmart'

In [36]:
bigmart.columns

Index(['ID', 'y', 'X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8',
       ...
       'X375', 'X376', 'X377', 'X378', 'X379', 'X380', 'X382', 'X383', 'X384',
       'X385'],
      dtype='object', length=378)